// Service to generate complete React websites with folder structure
export class ReactWebsiteService {
  static generateReactWebsiteFiles(prompt: string, htmlContent?: string): Record<string, string> {
    // Generate a complete React website with folder structure based on the prompt
    const projectName = this.extractProjectName(prompt) || 'my-react-app';
    
    // Create package.json
    const packageJson = JSON.stringify({
      "name": projectName,
      "version": "0.1.0",
      "private": true,
      "dependencies": {
        "react": "^18.2.0",
        "react-dom": "^18.2.0",
        "react-scripts": "5.0.1"
      },
      "scripts": {
        "start": "react-scripts start",
        "build": "react-scripts build",
        "test": "react-scripts test",
        "eject": "react-scripts eject"
      },
      "browserslist": {
        "production": [
          ">0.2%",
          "not dead",
          "not op_mini all"
        ],
        "development": [
          "last 1 chrome version",
          "last 1 firefox version",
          "last 1 safari version"
        ]
      }
    }, null, 2);
    
    // Create public/index.html - use AI-generated HTML or default
    const publicIndexHtml = htmlContent && htmlContent.trim() !== '' 
      ? this.convertHtmlToReactCompatible(htmlContent)
      : `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <link rel="icon" href="/favicon.ico" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="theme-color" content="#000000" />
    <meta name="description" content="Web site created using AI Agent" />
    <title>${projectName}</title>
  </head>
  <body>
    <noscript>You need to enable JavaScript to run this app.</noscript>
    <div id="root"></div>
  </body>
</html>`;
    
    // Create public/manifest.json
    const publicManifestJson = JSON.stringify({
      "short_name": projectName,
      "name": `${projectName} - AI Generated`,
      "icons": [
        {
          "src": "favicon.ico",
          "sizes": "64x64 32x32 24x24 16x16",
          "type": "image/x-icon"
        }
      ],
      "start_url": ".",
      "display": "standalone",
      "theme_color": "#000000",
      "background_color": "#ffffff"
    }, null, 2);
    
    // Create public/robots.txt
    const publicRobotsTxt = `# https://www.robotstxt.org/robotstxt.html
User-agent: *
Disallow:`;
    
    // Create src/index.js
    const srcIndexJs = `import React from 'react';
import { createRoot } from 'react-dom/client';
import './index.css';
import App from './App';

const container = document.getElementById('root');
const root = createRoot(container);
root.render(<App />);`;
    
    // Create src/index.css
    const srcIndexCss = `body {
  margin: 0;
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Oxygen',
    'Ubuntu', 'Cantarell', 'Fira Sans', 'Droid Sans', 'Helvetica Neue',
    sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

code {
  font-family: source-code-pro, Menlo, Monaco, Consolas, 'Courier New',
    monospace;
}`;
    
    // Create src/App.js - use AI-generated HTML or default
    const srcAppJs = htmlContent && htmlContent.trim() !== ''
      ? this.convertHtmlToReactComponent(htmlContent, projectName)
      : `import React from 'react';
import './App.css';

function App() {
  return (
    <div className="App">
      <header className="App-header">
        <h1>${projectName}</h1>
        <p>Your React application content will appear here.</p>
      </header>
    </div>
  );
}

export default App;`;
    
    // Create src/App.css
    const srcAppCss = `.App {
  text-align: center;
}

.App-header {
  background-color: #282c34;
  padding: 20px;
  color: white;
  min-height: 100vh;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
}

.App-header h1 {
  margin: 0;
  font-size: 2.5rem;
}`;
    
    // Create README.md
    const readmeMd = `# ${projectName}

This is a React application generated by AI Agent.

## Available Scripts

In the project directory, you can run:

### \`npm start\`

Runs the app in the development mode.\
Open [http://localhost:3000](http://localhost:3000) to view it in your browser.

The page will reload when you make changes.\
You may also see any lint errors in the console.

### \`npm test\`

Launches the test runner in the interactive watch mode.\

### \`npm run build\`

Builds the app for production to the \`build\` folder.\
It correctly bundles React in production mode and optimizes the build for the best performance.

The build is minified and the filenames include the hashes.\
Your app is ready to be deployed!

## Learn More

You can learn more in the [Create React App documentation](https://facebook.github.io/create-react-app/docs/getting-started).

To learn React, check out the [React documentation](https://reactjs.org/).`;

    // Return all files as a record for the ZIP file
    return {
      'package.json': packageJson,
      'public/index.html': publicIndexHtml,
      'public/manifest.json': publicManifestJson,
      'public/robots.txt': publicRobotsTxt,
      'src/index.js': srcIndexJs,
      'src/index.css': srcIndexCss,
      'src/App.js': srcAppJs,
      'src/App.css': srcAppCss,
      'README.md': readmeMd
    };
  }

  static convertHtmlToReactCompatible(html: string): string {
    // Convert HTML to be React-compatible by ensuring proper DOCTYPE and structure
    if (html.includes('<!DOCTYPE html>')) {
      return html;
    }
    
    // If no DOCTYPE, wrap in proper HTML structure
    return `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>AI Generated App</title>
  </head>
  <body>
    ${html}
  </body>
</html>`;
  }

  static convertHtmlToReactComponent(html: string, projectName: string): string {
    // Extract body content from HTML
    let bodyContent = html;
    
    // Remove HTML, head, and body tags if present
    if (html.includes('<body>')) {
      const bodyStart = html.indexOf('<body>') + 6;
      const bodyEnd = html.indexOf('</body>');
      bodyContent = html.substring(bodyStart, bodyEnd);
    }
    
    // Remove script tags
    bodyContent = bodyContent.replace(/<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi, '');
    
    // Convert inline styles to React style objects (simplified)
    bodyContent = bodyContent.replace(/style="([^"]*)"/g, (match, styleContent) => {
      // Convert CSS style to React style object
      const styleObj = styleContent.split(';').reduce((obj, rule) => {
        const [key, value] = rule.split(':').map(s => s.trim());
        if (key && value) {
          // Convert kebab-case to camelCase
          const camelKey = key.replace(/-([a-z])/g, (g) => g[1].toUpperCase());
          obj[camelKey] = value;
        }
        return obj;
      }, {} as Record<string, string>);
      
      // Convert to JSON string
      return `style={${JSON.stringify(styleObj)}}`;
    });
    
    // Convert class to className
    bodyContent = bodyContent.replace(/class=/g, 'className=');
    
    return `import React from 'react';
import './App.css';

function App() {
  return (
    <div className="App">
      ${bodyContent}
    </div>
  );
}

export default App;`;
  }

  static generatePreviewHtml(prompt: string): string {
    // Generate a minimal HTML file for preview
    const projectName = this.extractProjectName(prompt) || 'my-react-app';
    
    // Create a minimal HTML file
    return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${projectName}</title>
    <style>
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
            margin: 0;
            padding: 20px;
            background-color: #f5f5f5;
        }
        .container {
            max-width: 1200px;
            margin: 0 auto;
            background: white;
            border-radius: 8px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
            padding: 30px;
        }
        header {
            background: #282c34;
            color: white;
            padding: 20px;
            border-radius: 8px;
            margin-bottom: 30px;
            text-align: center;
        }
        h1 {
            margin: 0;
            font-size: 2.5rem;
        }
    </style>
</head>
<body>
    <div class="container">
        <header>
            <h1>${projectName}</h1>
        </header>
        <main>
            <p>Your React application will appear here. Ask the AI to generate specific content for your website.</p>
        </main>
    </div>
</body>
</html>`;
  }

  static extractProjectName(prompt: string): string | null {
    // Extract project name from prompt
    const patterns = [
      /create a react website for (\w+)/i,
      /create a (\w+) website/i,
      /build a (\w+) app/i,
      /make a (\w+) site/i
    ];
    
    for (const pattern of patterns) {
      const match = prompt.match(pattern);
      if (match) {
        return match[1];
      }
    }
    
    return null;
  }
  
  static isReactWebsiteRequest(prompt: string): boolean {
    const reactKeywords = ['react', 'website', 'app', 'web application', 'frontend'];
    const lowerPrompt = prompt.toLowerCase();
    
    return reactKeywords.some(keyword => lowerPrompt.includes(keyword));
  }
}